// app.get("/delete", async (req, res) => {
//   data.map(async (value) => {
//     try {
//       let pasteData = await Event.create(value);
//       console.log(pasteData);
//     } catch (error) {
//       console.log("----error-----" + error);
//     }
//   });
//   res.send("ok...");
// });

// data = [
//   {
//     Eventname: "Robo War",
//     Eventmentor: "Gaurav shukla",
//     Eventmentoremail: "grvshukla24@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 6,
//     EventClub: "ROBOTRAX CLUB",
//     EventCode: "011",
//   },
//   {
//     Eventname: "Robo Race",
//     Eventmentor: "Gaurav shukla",
//     Eventmentoremail: "grvshukla24@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 4,
//     EventClub: "ROBOTRAX CLUB",
//     EventCode: "012",
//   },
//   {
//     Eventname: "Line Follower Robot",
//     Eventmentor: "Gaurav shukla",
//     Eventmentoremail: "grvshukla24@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 4,
//     EventClub: "ROBOTRAX CLUB",
//     EventCode: "013",
//   },
//   {
//     Eventname: "Robo Soccer",
//     Eventmentor: "Gaurav shukla",
//     Eventmentoremail: "grvshukla24@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 5,
//     EventClub: "ROBOTRAX CLUB",
//     EventCode: "014",
//   },
//   {
//     Eventname: "Maze Solver",
//     Eventmentor: "Gaurav shukla",
//     Eventmentoremail: "grvshukla24@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 4,
//     EventClub: "ROBOTRAX CLUB",
//     EventCode: "015",
//   },
//   {
//     Eventname: "Drone Race",
//     Eventmentor: "Shubham singh",
//     Eventmentoremail: "shubham2230singh@gmail.com",
//     Grouped: true,
//     Minparticipation: 1,
//     Maxparticipation: 5,
//     EventClub: "SYNERGY CLUB",
//     EventCode: "021",
//   },
//   {
//     Eventname: "Aqua Race",
//     Eventmentor: "Shubham singh",
//     Eventmentoremail: "shubham2230singh@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 4,
//     EventClub: "SYNERGY CLUB",
//     EventCode: "022",
//   },
//   {
//     Eventname: "Robo Rumble",
//     Eventmentor: "Shubham singh",
//     Eventmentoremail: "shubham2230singh@gmail.com",
//     Grouped: true,
//     Minparticipation: 3,
//     Maxparticipation: 5,
//     EventClub: "SYNERGY CLUB",
//     EventCode: "023",
//   },
//   {
//     Eventname: "Drag & Place",
//     Eventmentor: "Shubham singh",
//     Eventmentoremail: "shubham2230singh@gmail.com",
//     Grouped: true,
//     Minparticipation: 3,
//     Maxparticipation: 5,
//     EventClub: "SYNERGY CLUB",
//     EventCode: "024",
//   },
//   {
//     Eventname: "Junk-War",
//     Eventmentor: "Shubham singh",
//     Eventmentoremail: "shubham2230singh@gmail.com",
//     Grouped: false,

//     EventClub: "SYNERGY CLUB",
//     EventCode: "025",
//   },
//   {
//     Eventname: "Chain reaction",
//     Eventmentor: "Anshul Johari",
//     Eventmentoremail: "johari.anshul8@gmail.com",
//     Grouped: true,
//     Minparticipation: 3,
//     Maxparticipation: 5,
//     EventClub: "AERONAUTICS CLUB",
//     EventCode: "031",
//   },
//   {
//     Eventname: "The Micrones",
//     Eventmentor: "Anshul Johari",
//     Eventmentoremail: "johari.anshul8@gmail.com",
//     Grouped: false,
//     EventClub: "AERONAUTICS CLUB",
//     EventCode: "032",
//   },
//   {
//     Eventname: "Glider Plane",
//     Eventmentor: "Anshul Johari",
//     Eventmentoremail: "johari.anshul8@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 4,
//     EventClub: "AERONAUTICS CLUB",
//     EventCode: "033",
//   },
//   {
//     Eventname: "CAD Tricks",
//     Eventmentor: "Anshul Johari",
//     Eventmentoremail: "johari.anshul8@gmail.com",
//     Grouped: false,
//     EventClub: "AERONAUTICS CLUB",
//     EventCode: "034",
//   },
//   {
//     Eventname: "Web Battle",
//     Eventmentor: "Tej singh",
//     Eventmentoremail: "tejsinghvns2002@gmail.com",
//     Grouped: false,
//     EventClub: "EQUINOX & ILLUMINATI CLUB",
//     EventCode: "041",
//   },
//   {
//     Eventname: "Beat-The-Bug",
//     Eventmentor: "Tej singh",
//     Eventmentoremail: "tejsinghvns2002@gmail.com",
//     Grouped: false,
//     EventClub: "EQUINOX & ILLUMINATI CLUB",
//     EventCode: "042",
//   },
//   {
//     Eventname: "Db Knight",
//     Eventmentor: "Tej singh",
//     Eventmentoremail: "tejsinghvns2002@gmail.com",
//     Grouped: false,
//     EventClub: "EQUINOX & ILLUMINATI CLUB",
//     EventCode: "043",
//   },
//   {
//     Eventname: "C-Experts",
//     Eventmentor: "Tej singh",
//     Eventmentoremail: "tejsinghvns2002@gmail.com",
//     Grouped: false,
//     EventClub: "EQUINOX & ILLUMINATI CLUB",
//     EventCode: "044",
//   },
//   {
//     Eventname: "Tech-Play",
//     Eventmentor: "Tej singh",
//     Eventmentoremail: "tejsinghvns2002@gmail.com",
//     Grouped: true,
//     Minparticipation: 1,
//     Maxparticipation: 6,
//     EventClub: "EQUINOX & ILLUMINATI CLUB",
//     EventCode: "045",
//   },
//   {
//     Eventname: "Arz kiya hai",
//     Eventmentor: "Suryansh shrivastav",
//     Eventmentoremail: "devanshsri2017@gmail.com",
//     Grouped: false,
//     EventClub: "LITERARAY CLUB",
//     EventCode: "051",
//   },
//   {
//     Eventname: "Let's Get Quizzical",
//     Eventmentor: "Suryansh shrivastav",
//     Eventmentoremail: "devanshsri2017@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 2,
//     EventClub: "LITERARAY CLUB",
//     EventCode: "052",
//   },
//   {
//     Eventname: "Spell-O-Ween",
//     Eventmentor: "Suryansh shrivastav",
//     Eventmentoremail: "devanshsri2017@gmail.com",
//     Grouped: false,
//     EventClub: "LITERARAY CLUB",
//     EventCode: "053",
//   },
//   {
//     Eventname: "Escape The Room",
//     Eventmentor: "Suryansh shrivastav",
//     Eventmentoremail: "devanshsri2017@gmail.com",
//     Grouped: true,
//     Minparticipation: 3,
//     Maxparticipation: 3,
//     EventClub: "LITERARAY CLUB",
//     EventCode: "054",
//   },
//   {
//     Eventname: "Word Bee",
//     Eventmentor: "Suryansh shrivastav",
//     Eventmentoremail: "devanshsri2017@gmail.com",
//     Grouped: false,
//     EventClub: "LITERARAY CLUB",
//     EventCode: "055",
//   },
//   {
//     Eventname: "Polaroid Exposure",
//     Eventmentor: "Shubhi Saxena",
//     Eventmentoremail: "shubhisaxena829@gmail.com",
//     Grouped: false,
//     EventClub: "MRC CLUB",
//     EventCode: "061",
//   },

//   {
//     Eventname: "Pictograph/Logograph Designing",
//     Eventmentor: "Shubhi Saxena",
//     Eventmentoremail: "shubhisaxena829@gmail.com",
//     Grouped: false,
//     EventClub: "MRC CLUB",
//     EventCode: "062",
//   },
//   {
//     Eventname: "Pharma desk",
//     Eventmentor: "Shruti saxena",
//     Eventmentoremail: "saxenashruti422@gmail.com",
//     Grouped: true,
//     Minparticipation: 1,
//     Maxparticipation: 3,
//     EventClub: "PHARMQUIMICA CLUB",
//     EventCode: "071",
//   },
//   {
//     Eventname: "Collage-O-Fact",
//     Eventmentor: "Shruti saxena",
//     Eventmentoremail: "saxenashruti422@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 2,
//     EventClub: "PHARMQUIMICA CLUB",
//     EventCode: "072",
//   },
//   {
//     Eventname: "Pioneerdom",
//     Eventmentor: "Shruti saxena",
//     Eventmentoremail: "saxenashruti422@gmail.com",
//     Grouped: true,
//     Minparticipation: 2,
//     Maxparticipation: 2,
//     EventClub: "PHARMQUIMICA CLUB",
//     EventCode: "073",
//   },
//   {
//     Eventname: "Pharmesquisser",
//     Eventmentor: "Shruti saxena",
//     Eventmentoremail: "saxenashruti422@gmail.com",
//     Grouped: false,
//     EventClub: "PHARMQUIMICA CLUB",
//     EventCode: "074",
//   },
//   {
//     Eventname: "Technical Painting",
//     Eventmentor: "Vaishnavi Sharma",
//     Eventmentoremail: "vaishnavhisharma9909@gmai.com",
//     Grouped: false,
//     EventClub: "DESIGN CLUB",
//     EventCode: "081",
//   },
//   {
//     Eventname: "Multimedia Art",
//     Eventmentor: "Vaishnavi Sharma",
//     Eventmentoremail: "vaishnavhisharma9909@gmai.com",
//     Grouped: false,
//     EventClub: "DESIGN CLUB",
//     EventCode: "082",
//   },
//   {
//     Eventname: "Best Out of Waste",
//     Eventmentor: "Vaishnavi Sharma",
//     Eventmentoremail: "vaishnavhisharma9909@gmai.com",
//     Grouped: false,
//     EventClub: "DESIGN CLUB",
//     EventCode: "083",
//   },
//   {
//     Eventname: "Quill The Techvyom",
//     Eventmentor: "Vaishnavi Sharma",
//     Eventmentoremail: "vaishnavhisharma9909@gmai.com",
//     Grouped: false,
//     EventClub: "DESIGN CLUB",
//     EventCode: "084",
//   },
//   {
//     Eventname: "BGMI",
//     Eventmentor: "TYRO",
//     Eventmentoremail: "techvyomsrms@gmail.com",
//     Grouped: false,
//     EventClub: "LAN WAR",
//     EventCode: "091",
//   },
//   {
//     Eventname: "FIFA",
//     Eventmentor: "TYRO",
//     Eventmentoremail: "techvyomsrms@gmail.com",
//     Grouped: false,
//     EventClub: "LAN WAR",
//     EventCode: "092",
//   },
//   {
//     Eventname: "Mini-Militia",
//     Eventmentor: "TYRO",
//     Eventmentoremail: "techvyomsrms@gmail.com",
//     Grouped: true,
//     Minparticipation: 1,
//     Maxparticipation: 5,
//     EventClub: "LAN WAR",
//     EventCode: "093",
//   },
//   {
//     Eventname: "Tech Gallery-Medical",
//     Eventmentor: "TYRO",
//     Eventmentoremail: "techvyomsrms@gmail.com",
//     Grouped: false,
//     EventClub: "OPEN EVENTS",
//     EventCode: "101",
//   },
//   {
//     Eventname: "Tech Gallery-Technical engineering",
//     Eventmentor: "TYRO",
//     Eventmentoremail: "techvyomsrms@gmail.com",
//     Grouped: false,
//     EventClub: "OPEN EVENTS",
//     EventCode: "102",
//   },
//   {
//     Eventname: "Tech Quiz",
//     Eventmentor: "Tej singh",
//     Eventmentoremail: "tejsinghvns2002@gmail.com",
//     Grouped: false,
//     EventClub: "OPEN EVENTS",
//     EventCode: "103",
//   },
//   {
//     Eventname: "PLC Designing",
//     Eventmentor: "Shubham",
//     Eventmentoremail: "shubham2230singh@gmail.com",
//     Grouped: false,
//     EventClub: "OPEN EVENTS",
//     EventCode: "104",
//   },
//   {
//     Eventname: "3D-Printing",
//     Eventmentor: "Gaurav shukla",
//     Eventmentoremail: "grvshukla24@gmail.com",
//     Grouped: false,
//     EventClub: "OPEN EVENTS",
//     EventCode: "105",
//   },
// ];
